name: mtm
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.0-80.1.beta <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.1
  flutter: 
    sdk: flutter
  neon: ^0.1.0
  flutter_svg: ^1.0.3
  show_up_animation: ^2.0.0
  flutter_native_splash: ^2.1.6
  flutter_dotenv: ^5.0.2
  youtube_player_flutter: ^8.1.0
  url_launcher: ^6.1.6

dev_dependencies: 
  flutter_lints: ^1.0.0
  lints: 1.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/images/
    - .env

  fonts:
    - family: Ar
      fonts:
        - asset: assets/fonts/ar.ttf
    
    - family: En
      fonts:
        - asset: assets/fonts/en.ttf

flutter_native_splash:
  color: "#010001"
  image: assets/images/logo.png
