import 'package:get/get.dart';
class LocaleString extends Translations{
  @override
  // TODO: implement keys
  Map<String, Map<String, String>> get keys => {
    'en_US':{
      "services" : "Serivces",
      "offers" : "Special Offers",
      "ask" : "Ask Me",
      "videos" : "Videos",
      "articles" : "Articles",
      "checkup" : "Regular Checkups",
      "centers" : "Service Centers",
      "6m" : "6 Months",
      "3m" : "3 Months",
      "1m" : "1 Month",
      "1y" : "1 Year",
      "free" : "Free",
      "car_name" : "Car Name",
      "my_vehicles" : "My Vehicles",
      "my_profile" : "My Profile",
      "my_services" : "My Services",
      "messages" : "Messages",
    },
    'ar_EG':{
      "login_by_code" : "تسجيل الدخول بالكود",
      "someone_calls_waiter" : "هناك احد جاهز للطلب.",
      "got_it" : "حسناً",
     'touch_any_where':'المس الشاشة لعمل طلب جديد',
      'enter_code':'ادخل كود المستخدم',
      'enter_pin':'ادخل الرقم السري',
      'new_code':'اعادة ادخال كود المستخدم',
      'emp_code_err':'كود المستخدم غير موجود برجاء اعادة المحاولة',
      "login_by_qr" : "تسجيل الدخول بأستخدام البار كود",
      "emp_password_err" : "رقم المرور غير صحيح",
      'welcome':'اهلا بك',
      "not_allowed":"ليس لديك الصلاحية لتنفيذ هذا الأمر.",
      "Working_without_cheque":"مشغولة - غير محصلة",
      "Working_with_cheque":" مشغولة - محصلة ",
      "paused":"هناك شخص اخر يتعامل علي هذه الطاولة",
      "unauthorized":"غير مصرح لك بالتعامل علي هذه الطاولة",
      "error": "خطأ",
      "connection_error": "لا نستطيع الوصول الي الخادم, برجاء مراجعة الأتصال و اعادة المحاولة",
      "login_desc" : "نريد ان نتأكد من هويتك. اختر الطريقة التي تريد ان تسجل بها دخولك",
      "subtotal" : "اجمالي فرعي",
      "total" : "اجمالي",
      "discount" : "خصم",
      "name" : "الاسم",
      "price" : "السعر",
      "order_finished" : "تم الانتهاء من هذا الطلب",
      "tax" : "الضريبة",
      "qnt" : "الكمية",
      "free" : "غير مشغولة",
      "items" : "عرض ",
      "send" : "ارسال",
      "print" : "طباعة",
      "addons" : "الإضافات",
      "modifiers" : "معدلات الصنف",
      "split_cheq" : "فصل الشيك",
      "transfer" : "نقل الأصناف",
      "change_table" : "تغيير الطاولة",
      "change_customer" : "تغيير العميل",
      "change_waiter":"تغيير النادل",
      "no_of_guests" : "تغيير عدد المقاعد",
      "apply_Discount" : "تطبيق خصم",
      "choose_table" : "اختيار الطاولة",
      "transfer_items" : "اختيار الأصناف للتحويل",
      "continue" : "استمرار",
      "cancel" : "الغاء",
      "submit" : "تأكيد",
      "minimum" : "الحد الادني",
      "not_allowed_before_send" : "لا يمكن نتفيذ هذا الأمر قبل ارسال الطلب مرة.",
      "choose_discount" : "نسبة الخصم",
      "comment" : "الملاحظات",
      "apply" : "تطبيق",
      "next" : "التالي",
      "done" : "تم",
    },
  };
}